  <link rel="stylesheet" href="timeline/timeline.css">

<section class="ps-timeline-sec" style="opacity: 0.5">
        <div class="container">
            <ol class="ps-timeline">
                <li>
                    <div class="img-handler-top">
                      <!-- <img width="30%" src="timeline/branch.png" alt=""/> -->
                       <br><b style="font-weight: bold;font-size: 20px;">Sales </b>
                    </div>
                    <div class="ps-bot">
                        <p> Sales Person will get the Lead of Customer from Social Media Marketing ... etc or gets an request of existing customer via Mail or Call</p>
                    </div>
                    <span class="ps-sp-top">01</span>
                </li>
                <li>
                    <div class="img-handler-bot">
                         <!-- <img width="30%" src="timeline/branch.png" alt=""/> -->
                         <br><b style="font-weight: bold;font-size: 20px;"> Sales Manager</b>
                    </div>
                    <div class="ps-top">
                        <p>Sales Manager will Make sure that the Lead Generated by Sales is Correct ! Approve It !</p>
                    </div>
                    <span class="ps-sp-bot">02</span>
                </li>
                <li>
                    <div class="img-handler-top">
                      <!-- <img width="30%" src="timeline/branch.png" alt=""/> -->
                       <br><b style="font-weight: bold;font-size: 20px;">Sales </b>
                    </div>
                    <div class="ps-bot">
                        <p>Sales Person Will Generate a Local RFQ or "QUOTATION" for that Lead </p>
                    </div>
                    <span class="ps-sp-top">03</span>
                </li>
              
            </ol>
        </div>
    </section>
