  <link rel="stylesheet" href="timeline/timeline.css">

<section class="ps-timeline-sec" style="opacity: 0.5">
        <div class="container">
            <ol class="ps-timeline">
                <li>
                    <div class="img-handler-top">
                        <img width="20%" src="timeline/generatingpo.png" alt=""/> 
                        <br><b style="font-weight: bold;font-size: 20px;">Warehouse </b>
                    </div>
                    <div class="ps-bot">
                        <p> Warehouse Employee Will Generate a  Local PO <b class="txt-primary"> Manually </b> OR Generate from <b class="txt-primary"> Branch RQ</b> based on some conditions</p>
                    </div>
                    <span class="ps-sp-top">01</span>
                </li>
                <li>
                    <div class="img-handler-bot">
                       <img width="50%" src="timeline/managerapproving.png" alt=""/> <br><b style="font-weight: bold;font-size: 20px;">Warehouse Manager</b>
                    </div>
                    <div class="ps-top">
                        <p>Warehouse Manager Will Make sure that Local PO Generated by Warehouse is Correct or Not! <Br> Warehouse Manager will Approve It & Mail to Supplier!</p>
                    </div>
                    <span class="ps-sp-bot">02</span>
                </li>
                <li>
                    <div class="img-handler-top">
                      <img width="70%" src="timeline/suppliersendinggoods.png" alt=""/><br><br><br><b style="font-weight: bold;font-size: 20px;">Supplier </b>
                    </div>
                    <div class="ps-bot">
                        <p>Supplier Will Send the Products as per Local PO. </p>
                    </div>
                    <span class="ps-sp-top">03</span>
                </li>
                <li>
                    <div class="img-handler-bot">
                        <img width="50%" src="timeline/managerchecking2.png" alt=""/> <br><b style="font-weight: bold;font-size: 20px;">Good Receipt [Warehouse]</b>
                    </div>
                    <div class="ps-top">
                        <p>Warehouse will Check the Items Received by Supplier and He Will make   <b class="txt-primary"> Purchase Receipt </b> which he can generate from  <b class="txt-primary"> Local PO </b></p>
                    </div>
                    <span class="ps-sp-bot">04</span>
                </li>  

                 <li>
                    <div class="img-handler-top">
                       <img width="70%" src="timeline/stockincreased.png" alt=""/>  <br><b style="font-weight: bold;font-size: 20px;">Good Receipt Approval [Warehouse Manager]</b>
                    </div>
                    <div class="ps-bot">
                        <p>Warehouse Manager will Re-Check the Items and POST IT and Give the Purchase Receipt to Office Boy. <br>  <b class="txt-primary"> Based on that Stock will Increase.</b></p>
                    </div>
                    <span class="ps-sp-top">05</span>
                </li>
            </ol>
        </div>
    </section>
