  <link rel="stylesheet" href="timeline/timeline.css">

<section class="ps-timeline-sec" style="opacity: 0.5">
        <div class="container">
            <ol class="ps-timeline">
                <li>
                    <div class="img-handler-top">
                       <!-- <img src="http://www.physology.co.uk/wp-content/uploads/2016/02/ps-elem_03.png" alt=""/> --><br><b style="font-weight: bold;font-size: 20px;">Warehouse </b>
                    </div>
                    <div class="ps-bot">
                        <p> Warehouse Employee Will Generate a Purchase Receipt from Local PO or Manually. </p>
                    </div>
                    <span class="ps-sp-top">01</span>
                </li>
                <li>
                    <div class="img-handler-bot">
                        <!-- <img src="http://www.physology.co.uk/wp-content/uploads/2016/02/ps-elem_13.png" alt=""/> --><br><b style="font-weight: bold;font-size: 20px;">Warehouse Manager</b>
                    </div>
                    <div class="ps-top">
                        <p>Manager Will Make sure that the Purchase Receipt Invoice Generated by Warehouse Employee is Correct ! Approve It & POST It! After POSTING the Stock Increases</p>
                    </div>
                    <span class="ps-sp-bot">02</span>
                </li>
             
            </ol>
        </div>
    </section>
